# Cut a release whenever a new tag is pushed to the repo.
name: Release

on:
  workflow_dispatch:
  # Can be triggered from the tag.yaml workflow
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
  # Or, developers can manually push a tag from their clone
  push:
    tags:
      - "v*.*.*"
permissions:
  id-token: write
  attestations: write
  contents: write
jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@57bfc4913c74f8e58ab1743cb92d4c889ae77675
    with:
      release_files: rules_oci-*.tar.gz
      prerelease: false
      docs: true

      tag_name: ${{ inputs.tag_name || github.ref_name }}
  publish:
    needs: release
    uses: ./.github/workflows/publish.yaml
    with:
      tag_name: ${{ inputs.tag_name || github.ref_name }}
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
